project:
  name: validation-api
  version: 0.0.1
  debug: true
  description: |
    描述第一行
    描述第二行

mysql:
  default:
    host: 127.0.0.1
    port: 3306
    user: root
    passwd: naobo
    db: test_db
    pool_size: 10
    max_overflow: 5
    pool_timeout: 30
    pool_recycle: 3600
    echo: false
    echo_pool: false
    connect_timeout: 10
    execute_timeout: 10

kafka:
  default:
    bootstrap_servers:
      - host: localhost
        port: 19092
    client_id: validation
    acks: all
    compression_type: zstd
    max_batch_size: 16384
    linger_ms: 0
    request_timeout_ms: 1000
    retry_backoff_ms: 100

redis:
  default:
    host: 127.0.0.1
    port: 6379
    password: ""
    db: 0
    pool_size: 10
    connect_timeout: 10
    socket_timeout: 10