kafka:
  default:
    bootstrap_servers:
      - host: 127.0.0.1
        port: 29092
    client_id: pytest-client-id
    acks: all
    compression_type: zstd
    max_batch_size: 16384
    linger_ms: 0
    request_timeout_ms: 1000
    retry_backoff_ms: 100

mongo:
  default:
    hosts:
      - host: 127.0.0.1
        port: 27017
    user: root
    passwd: root
    db: test_db
    pool_size: 5
    pool_timeout: 10
    pool_recycle: 60
    connect_timeout: 3
    execute_timeout: 3

mysql:
  default:
    host: 127.0.0.1
    port: 3306
    user: root
    passwd: root
    db: test_db
    pool_size: 10
    max_overflow: 5
    pool_timeout: 30
    pool_recycle: 3600
    echo: false
    echo_pool: false
    connect_timeout: 10
    execute_timeout: 10

redis:
  default:
    host: 127.0.0.1
    port: 6379
    password: ""
    db: 10
    pool_size: 10
    connect_timeout: 10
    socket_timeout: 10

feishu:
  enable: true
  webhooks:
    - https://open.feishu.cn/open-apis/bot/v2/hook/****

project:
  name: pytest
  id: 0
  description: pytest
  version: 0.0.1
  key: pytest_key
